version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    ignore:
        # No more JDK 8 support
      - dependency-name: org.junit.vintage:junit-vintage-engine
        versions: "[6.0.0,)"
